### ISSUE TITLE
Python sends commands but simulator drone does not move

### ISSUE THREAD

**Issue by fabiankuenzer** [dbaldwin/DroneBlocks-Tello-Simulator-With-Python#3]
I successfully set up the Python code as described in the README. The browser is configured to accept insecure content and the simulator key is copied into the code. When I run the code, the terminal prints `publishing command: takeoff,24a2fec8-5c87-49ac-97ab-64eabdf3ba98` but the drone in the simulator does not move. I use Python 3.11.3. I successfully used the simulator in October 2023. Now it stopped working.

**Comment by dbaldwin** [comment]
@fabiankuenzer I just saw your support request regarding the DroneBlocks Python sim. I'll take a look tomorrow and see what I can find out.

**Comment by dbaldwin** [comment]
@fabiankuenzer it turns out the message broker, which is the middleware between your python client and our sim, had gone unresponsive. We've brought it back up and you should be good to go. Please let us know if that's not the case. Will leave this open in the meantime.

**Comment by fabiankuenzer** [comment]
@dbaldwin Thank you for your help, now the simulator works as expected 🚀

**Comment by dbaldwin** [comment]
@fabiankuenzer thanks. Also, in the future feel free to join our Discord if you ever want to chat about the sim. https://discord.gg/vQ6MRyfcUA

**Comment by vpr1995** [comment]
Hi, I think the MQTT Broker is down again. This is what the webpage console logs says 

` main.js:2 WebSocket connection to 'wss://mqtt.droneblocks.io:9001/' failed: `

**Comment by dbaldwin** [comment]
@vpr1995 sorry about that. Try it now. We have added some additional logic to restart the service if it dies.
